FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["InvestmentTracker.API.csproj", "./"]
RUN dotnet restore "./InvestmentTracker.API.csproj"

COPY . .
WORKDIR "/src/"
RUN dotnet build "InvestmentTracker.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "InvestmentTracker.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InvestmentTracker.API.dll"]